name = "walsync"
type = "javascript"
compatibility_date = "2024-01-12"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration (for local development)
build = { command = "npm run build" }
main = "dist"
